### ISSUE TITLE
Invariant crashes.  branch: akka-raft

### ISSUE THREAD

**Issue by colin-scott** [NetSys/demi-applications#2]
The logmatch invariant might be slightly incorrect. It caused this crash:

RaftChecks.scala, LogMatch invariant:

```
java.lang.IndexOutOfBoundsException: 6
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:51)
        at scala.collection.immutable.List.apply(List.scala:83)
        at pl.project13.scala.akka.raft.model.ReplicatedLog.apply(ReplicatedLog.scala:81)
        at runner.raftchecks.LogMatchChecker$$anonfun$checkActor$1.apply(RaftChecks.scala:237)
        at runner.raftchecks.LogMatchChecker$$anonfun$checkActor$1.apply(RaftChecks.scala:219)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
        at runner.raftchecks.LogMatchChecker.checkActor(RaftChecks.scala:219)
        at runner.raftchecks.RaftChecks.checkActor(RaftChecks.scala:179)
        at runner.raftchecks.RaftChecks$$anonfun$check$2.apply(RaftChecks.scala:140)
        at runner.raftchecks.RaftChecks$$anonfun$check$2.apply(RaftChecks.scala:138)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at runner.raftchecks.RaftChecks.check(RaftChecks.scala:138)
```

**Comment by colin-scott** [comment]
No longer seems to be an issue.
